# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-31 22:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Centre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle_centre', models.CharField(max_length=500, verbose_name='Centre de Sant\xe9')),
                ('situation', models.CharField(max_length=500, verbose_name='Situation Geographique du Centre')),
            ],
            options={
                'verbose_name': 'centre sanitaire',
                'verbose_name_plural': 'Centres Sanitaires',
            },
        ),
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=250, verbose_name='Region')),
                ('libelle', models.CharField(max_length=250, verbose_name='Commune')),
            ],
            options={
                'verbose_name': 'commune',
                'verbose_name_plural': 'Communes',
            },
        ),
        migrations.CreateModel(
            name='Mairie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maire', models.CharField(max_length=500, verbose_name='Nom et Prenoms du Maire')),
                ('telephone1', models.CharField(max_length=50, verbose_name='Telephone 1')),
                ('telephone2', models.CharField(blank=True, max_length=50, null=True, verbose_name='Telephone 2')),
                ('adresse', models.CharField(blank=True, max_length=100, verbose_name='Adresse Postale')),
                ('email', models.CharField(blank=True, max_length=100, verbose_name='Adresse Email')),
                ('site', models.CharField(blank=True, max_length=100, verbose_name='Site Web')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos')),
                ('Commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametres.Commune')),
            ],
        ),
        migrations.AddField(
            model_name='centre',
            name='centre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametres.Commune'),
        ),
    ]
