# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-01 02:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='centre',
            options={'verbose_name': 'centre de sante', 'verbose_name_plural': 'CENTRES DE SANTE'},
        ),
        migrations.AlterModelOptions(
            name='commune',
            options={'verbose_name': 'commune', 'verbose_name_plural': 'COMMUNES'},
        ),
        migrations.AlterModelOptions(
            name='mairie',
            options={'verbose_name': 'mairie', 'verbose_name_plural': 'MAIRIE'},
        ),
    ]
