# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-01 02:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extraits', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mention',
            options={'verbose_name': 'Mention', 'verbose_name_plural': 'MENTIONS EVENTUELLES'},
        ),
        migrations.AlterModelOptions(
            name='naissance',
            options={'verbose_name': 'Acte de naissance', 'verbose_name_plural': 'ACTES DE NAISSANCE'},
        ),
        migrations.AddField(
            model_name='naissance',
            name='jugement',
            field=models.CharField(default='non', max_length=5, verbose_name='TRANSCRIPTION DE JUGEMENT SUPPLETIF ?'),
        ),
        migrations.AddField(
            model_name='naissance',
            name='num_jugement',
            field=models.CharField(blank=True, max_length=255, verbose_name='PRECISER LE NUMERO DU JUGEMENT SUPPLETIF'),
        ),
        migrations.AlterField(
            model_name='jugement',
            name='date_naiss_pere',
            field=models.DateField(blank=True, verbose_name='Date de Naissance du Pere'),
        ),
        migrations.AlterField(
            model_name='jugement',
            name='lieu_naiss_pere',
            field=models.DateField(blank=True, verbose_name='Lieu de Naissance du Pere'),
        ),
        migrations.AlterField(
            model_name='jugement',
            name='officie',
            field=models.CharField(max_length=500, verbose_name='Nom et Prenoms Officie'),
        ),
        migrations.AlterField(
            model_name='mention',
            name='conjoint',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nom et Prenoms du CONJOINT(E)'),
        ),
        migrations.AlterField(
            model_name='mention',
            name='date_divorce',
            field=models.DateField(blank=True, max_length=250, verbose_name='Date du Divorce'),
        ),
        migrations.AlterField(
            model_name='mention',
            name='date_mariage',
            field=models.DateField(blank=True, verbose_name='Date du Mariage'),
        ),
        migrations.AlterField(
            model_name='mention',
            name='details_divorce',
            field=models.CharField(blank=True, max_length=250, verbose_name='Details Divorce'),
        ),
        migrations.AlterField(
            model_name='mention',
            name='heure_mariage',
            field=models.DateField(blank=True, verbose_name='Heure du Mariage'),
        ),
        migrations.AlterField(
            model_name='mention',
            name='lieu_mariage',
            field=models.CharField(blank=True, max_length=500, verbose_name='Lieu de Celebartion du Mariage'),
        ),
        migrations.AlterField(
            model_name='mention',
            name='numero',
            field=models.CharField(blank=True, max_length=5, unique=True, verbose_name='Numero Mariage'),
        ),
        migrations.AlterField(
            model_name='naissance',
            name='categorie',
            field=models.CharField(choices=[('ACTE DE NAISSANCES', (('normal', 'NORMAL'), ('copie', 'COPIE INTEGRALE / JUGEMENT SUPPLETIF'))), ('MENTIONS', (('mariage', 'ACTE DE MARIAGE'), ('deces', 'ACTE DE DECES')))], default='normal', max_length=150, verbose_name='Nature Document'),
        ),
    ]
