# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-01 02:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extraits', '0002_auto_20180601_0247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='naissance',
            name='jugement',
            field=models.CharField(choices=[('oui', 'OUI'), ('non', 'NON')], default='non', max_length=5, verbose_name='TRANSCRIPTION DE JUGEMENT SUPPLETIF ?'),
        ),
    ]
